---
title: "Covid91 vaccine study Final2022"
author: "Kaylie Brehm"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final_Data.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#FinalData$infected <- relevel(FinalData$infected,ref="OK")
Male = filter(FinalData, sex =="M")
Female = filter(FinalData, sex =="F")
Gay = filter(FinalData, LGBTQ =="gay")
DrugUser = filter(FinalData, DrugUser =="yes")
```

# Introduction

A new  preventative vaccine (covid91) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.



## Hypothesis and Method

$H_0$: The preventative vaccine, covid91, is not effective for this particular subgroup (male, female, gay, or drug user).

$H_A$: The preventative vaccine, covid91, is effective for this particular subgroup (male, female, gay, or drug user).

Whether an individual was infected or not is categorical. Whether an individual was male or female is categorical. Whether an individual is gay or straight is categorical. Whether an individual is a drug user or not is categorical. I will use a CAT~CAT analysis to determine whether the vaccine was effective for each particular subgroup. In each subgroup section, I will use a bar chart (graphical descriptive results), a data table (numerical descriptive results), a chi-squared test (inferential descriptive results), and a fisher exact test (inferential descriptive results). Then, in each subgroup section, I will analyze the data and give a conclusion. Once each subgroup is completed, I will give my overall thoughts thoughts on the study. 

## Male

### Graphical Descriptive Results


### Numerical Descriptive Results 


### Inferential Descriptive Results 


### Conclusion



## Female

### Graphical Descriptive Results


### Numerical Descriptive Results 


### Inferential Descriptive Results 


### Conclusion



## Gay

### Graphical Descriptive Results


### Numerical Descriptive Results 


### Inferential Descriptive Results 


### Conclusion



## Drug User

### Graphical Descriptive Results


### Numerical Descriptive Results 


### Inferential Descriptive Results 


### Conclusion



# Final Thoughts and Discussion

